import { Inter } from 'next/font/google'
import './globals.css'
import { Footer, Header } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Digipro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='px-10'>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  )
}
